name: My first Github Workflow
on: [push]
jobs:
  Test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - run: python app.py
      - run: echo "Success"
      - name: Check out repository code
        uses: actions/checkout@v3
